services:
  mysql:
    image: mysql:8.0
    container_name: fitplate-mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: fitplate_prod
      MYSQL_USER: fitplate_prod_user
      MYSQL_PASSWORD: fitplate_prod
    ports:
      - "3308:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql

  backend:
    build: .
    container_name: fitplate-backend-prod
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/config/fitplate-prod.env

volumes:
  mysql_prod_data: