server {
    listen 80;
    server_name fit-plate.com www.fit-plate.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name fit-plate.com www.fit-plate.com;

    ssl_certificate /etc/nginx/certs/origin.pem;
    ssl_certificate_key /etc/nginx/certs/origin.key;

    location /api/ {
        proxy_pass http://backend:8080;

        proxy_connect_timeout 10s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}