name: Deploy Fitplate Backend

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Deploy branch: ${{ github.ref_name }}"

            if [ "${{ github.ref_name }}" = "dev" ]; then
              cd /home/ubuntu/apps/Fitplate-backend-dev
              git fetch origin dev
              git checkout dev
              git pull origin dev
              chmod +x gradlew
              ./gradlew clean build -x test
              sudo systemctl restart fitplate-dev
              sudo systemctl status fitplate-dev --no-pager
            fi

            if [ "${{ github.ref_name }}" = "main" ]; then
              cd /home/ubuntu/apps/Fitplate-backend-prod
              git fetch origin main
              git checkout main
              git pull origin main
              chmod +x gradlew
              ./gradlew clean build -x test
              sudo systemctl restart fitplate-prod
              sudo systemctl status fitplate-prod --no-pager
            fi
