name: Deploy Fitplate Backend

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "배포할 브랜치를 선택하세요."
        required: true
        default: dev
        type: choice
        options:
          - dev
          - main

run-name: Deploy ${{ inputs.target_branch }} backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            TARGET_BRANCH="${{ inputs.target_branch }}"
            echo "Deploy branch: ${TARGET_BRANCH}"

            if [ "${TARGET_BRANCH}" = "dev" ]; then
              cd /home/ubuntu/apps/Fitplate-backend-dev
              git fetch origin dev
              git checkout dev
              git pull origin dev
              chmod +x gradlew
              ./gradlew clean build -x test
              sudo systemctl restart fitplate-dev
              sudo systemctl status fitplate-dev --no-pager
            fi

            if [ "${TARGET_BRANCH}" = "main" ]; then
              cd /home/ubuntu/apps/Fitplate-backend-prod
              git fetch origin main
              git checkout main
              git pull origin main
              chmod +x gradlew
              ./gradlew clean build -x test
              sudo systemctl restart fitplate-prod
              sudo systemctl status fitplate-prod --no-pager
            fi
